spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flashlearn
    username: flashlearn
    password: flashlearn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate      # схему создаёт Flyway
    open-in-view: false
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb.core: info
